POST http://localhost:3333/videos
Content-Type: application/json


{
    "title": "Video eba",
    "description": "Esse é o video 01",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/e56ef4ec-45eb-4f79-ad91-9c62c0e7ea11
Content-Type: application/json

{
    "title": "Video 2000",
    "description": "Ma porra toda",
    "duration": 69
}

###

DELETE http://localhost:3333/videos/e56ef4ec-45eb-4f79-ad91-9c62c0e7ea11